### ISSUE TITLE
Not accepting a port

### ISSUE THREAD

**Issue by piecubed** [dart-lang/web_socket_channel#102]
Trying to connect to a websocket service i made thats listening on port 3300 on localhost...
related code:
`final ws = IOWebSocketChannel.connect("ws://localhost:3300")`
`Unhandled Exception: WebSocketChannelException: WebSocketChannelException: SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 42166`

I tried this with a Uri as well, same result.  The port is different each time.

**Comment by natebosch** [comment]
The error message is confusing, but the root problem is that the server is refusing the connection. The port printed in the  message is mislabeled - it's the local port, not the remote port. See https://github.com/dart-lang/sdk/issues/12693

The correct port is getting used, the problem looks like it lies on the server side. Maybe it's not listening on `localhost`? Stackoverflow may be able to offer more help than we can here.
