### ISSUE TITLE
NodeJS support

### ISSUE THREAD

**Issue by jaumard** [dart-lang/web_socket_channel#107]
Hello,

I'm trying to use dart2js to compile my dart package as a node package that I want to put on nom later.

Currently it doesn't work because `web_socket_channel` has no implementation for that runtime.

Is there a way to make this append ? Can I help ?

**Comment by natebosch** [comment]
You should be able to look at the implementation here to get an idea of how to accomplish this, but it isn't something we will plan on including in this package.

Generally it will be safe for you to `import 'package:web_socket_channel/web_socket_channel.dart';` and then write a class which `implements WebSocketChannel`.
