### ISSUE TITLE
First received message after connection needs waiting time!

### ISSUE THREAD

**Issue by hoekbrwr** [dart-lang/web_socket_channel#110]
I am experiencing a loss of the first data message after opening the socket. when  I start my app the WebSocket server immediately sends 2 messages to set some variables with actual initial values.
The first message only arrives without fault if I wait for about 200 msec to send the 2nd.
I have been looking into the debugger and find the 1st message gives a connectionState.index=1 and data=null.
This is the only problem I have with my app after that the com over the channel is flawless. 
I give here a piece of my code to  show what I am doing:
```dart
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: StreamBuilder(
        stream: widget.channel.stream,
        builder: (context, snapshot) {
          if (snapshot.hasData) {
            String val = snapshot.data;
            switch (val[0]) {
              case "H":
```

Any idea what is going on??? Can I use some waiting before snapshot hasData statement to prevent this.

**Comment by natebosch** [comment]
It looks like you are hitting a behavior of `StreamBuilder`. As far as I can tell this doesn't have anything to do with `web_socket_channel`.

The docs for `StreamBuilder` say:

> The builder is called at the discretion of the Flutter pipeline, and will thus receive a timing-dependent sub-sequence of the snapshots that represent the interaction with the stream.

From what I can tell `StreamBuilder` is allowed to swallow some events from the stream. If you can reproduce what you believe to be a bug in `web_socket_channel` feel free to comment with some code demonstrating the issue without `StreamBuilder` and we can investigate.

**Comment by hoekbrwr** [comment]
Thank you for your attention. However, I have been working around the problem and the app did what I was trying to achieve. It is not so interesting for me to do an investigation on this unexpected behaviour of the Streambuilder. However, I will remember this in the next cases in other app(s) in the future and I might raise a new more documented case. Better close this case for now!
