### ISSUE TITLE
is this supposed to work with flutter web?

### ISSUE THREAD

**Issue by tcerven** [dart-lang/web_socket_channel#116]
I don't think so because when I try to use it I get an 

> Unsupported operation: Platform._version

**Comment by nightrobin** [comment]
Try to import 'package:web_socket_channel/html.dart';

**Comment by tcerven** [comment]
> Try to import 'package:web_socket_channel/html.dart';

Thanks, nightrobin. All that was left was to change IOWebSocketChannel to HtmlWebSocketChannel and it works in flutter web. Really appreciate your help.
