### ISSUE TITLE
关于心跳的问题

### ISSUE THREAD

**Issue by SocietyYourBerotherMing** [dart-lang/web_socket_channel#126]
soket怎么添加心跳包,防止连接断开

**Comment by SocietyYourBerotherMing** [comment]
> use:
> 
> ```
> IOWebSocketChannel.connect(serverUrl, pingInteval: Duration(milliseconds:2000))
> ```
thanks

**Comment by Panxiaozhu** [comment]
> 
> 
> use:
> 
> ```
> IOWebSocketChannel.connect(serverUrl, pingInteval: Duration(milliseconds:2000))
> ```

It does not work. If you disconnect the network and then open the network, you will not be able to reconnect

**Comment by wapchief** [comment]
可以和服务端做个约定，他隔多少秒给你发个心跳，你再回一个

```

onData((message) {
      String type = jsonDecode(message)['msg_type'];
      var data = jsonDecode(message)['date'];
      switch (type) {
        //心跳
        case 'heartbeat':
          var msgData = {"Topic": "heartbeat"};
          _webSocket.sink.add(jsonEncode(msgData));
          lastHeartbeat = 1;
          break;
```
然后维护一个本地心跳，只要超过15秒没收到服务器的心跳，就重联，我这服务器给的是10秒，本地心跳是15秒
```
  static localHeart() {
    if (_timer != null && _timer.isActive) {
      return;
    }
    const timeout = const Duration(seconds: 15);
    _timer = Timer.periodic(timeout, (timer) {
      if (loginState == 1) {
        print("$loginState心跳状态：" + (lastHeartbeat == 1).toString());
        if (lastHeartbeat == 0) {
          socketConnect();
        } else {
          lastHeartbeat = 0;
        }
      }
    });
  }
```

**Comment by SocietyYourBerotherMing** [comment]
> 可以和服务端做个约定，他隔多少秒给你发个心跳，你再回一个
> 
> ```
> 
> onData((message) {
>       String type = jsonDecode(message)['msg_type'];
>       var data = jsonDecode(message)['date'];
>       switch (type) {
>         //心跳
>         case 'heartbeat':
>           var msgData = {"Topic": "heartbeat"};
>           _webSocket.sink.add(jsonEncode(msgData));
>           lastHeartbeat = 1;
>           break;
> ```
> 
> 然后维护一个本地心跳，只要超过15秒没收到服务器的心跳，就重联，我这服务器给的是10秒，本地心跳是15秒
> 
> ```
>   static localHeart() {
>     if (_timer != null && _timer.isActive) {
>       return;
>     }
>     const timeout = const Duration(seconds: 15);
>     _timer = Timer.periodic(timeout, (timer) {
>       if (loginState == 1) {
>         print("$loginState心跳状态：" + (lastHeartbeat == 1).toString());
>         if (lastHeartbeat == 0) {
>           socketConnect();
>         } else {
>           lastHeartbeat = 0;
>         }
>       }
>     });
>   }
> ```

楼上好像提出具体操作办法,这个库自己支持心跳包

**Comment by Panxiaozhu** [comment]
> 
> 
> 可以和服务端做个约定，他隔多少秒给你发个心跳，你再回一个
> 
> ```
> 
> onData((message) {
>       String type = jsonDecode(message)['msg_type'];
>       var data = jsonDecode(message)['date'];
>       switch (type) {
>         //心跳
>         case 'heartbeat':
>           var msgData = {"Topic": "heartbeat"};
>           _webSocket.sink.add(jsonEncode(msgData));
>           lastHeartbeat = 1;
>           break;
> ```
> 
> 然后维护一个本地心跳，只要超过15秒没收到服务器的心跳，就重联，我这服务器给的是10秒，本地心跳是15秒
> 
> ```
>   static localHeart() {
>     if (_timer != null && _timer.isActive) {
>       return;
>     }
>     const timeout = const Duration(seconds: 15);
>     _timer = Timer.periodic(timeout, (timer) {
>       if (loginState == 1) {
>         print("$loginState心跳状态：" + (lastHeartbeat == 1).toString());
>         if (lastHeartbeat == 0) {
>           socketConnect();
>         } else {
>           lastHeartbeat = 0;
>         }
>       }
>     });
>   }
> ```
还是得自己维护心跳包

**Comment by sleepreading** [comment]
建议增加一个特性: 断开重连. 可以当做连接参数. 或者可以自定义心跳回调.
