### ISSUE TITLE
allow to pass protocols to WebSocketChannel.connect

### ISSUE THREAD

**Issue by chandu0101** [dart-lang/web_socket_channel#132]
```
factory WebSocketChannel.connect(Uri uri) => platform.connect(uri);
```
there is no way to send sub-protocols atm.

**Comment by vmeretin** [comment]
+++

Also need `Map<String, dynamic> headers`

**Comment by V3lop5** [comment]
Also need headers.

@vmeretin did you find a workaround?

**Comment by vmeretin** [comment]
Protocols were added in 1.2.0. This issue can be closed.
