### ISSUE TITLE
Nullsafety version and release

### ISSUE THREAD

**Issue by Daegalus** [dart-lang/web_socket_channel#138]
Can we get a nullsafety version and release? My library uses Crypto and the Test package, and I can't publish a nullsafety version of my library because `test` depends on `web_socket_channel` which depends on the non-nullsafety version of `crypto`. `crypto` now has the `3.0.0-nullsafety.0` version of their library now.

I have been trying to release a nullsafety version of my library `uuid` for a while now, and crypto was the blocker. But now `pub lish` complains that I am trying to override a non-dev depenecy when I do an override for test because I directly depend on `crypto` and the override is overriding it too, not just test.

https://github.com/Daegalus/dart-uuid/issues/50 is the issue being tracked on my library.

**Comment by natebosch** [comment]
I have https://github.com/dart-lang/web_socket_channel/pull/139 out to allow the null safe `crypto` before we get the migration done here.

I think `analyzer` will be the blocker after that.

**Comment by Daegalus** [comment]
Thanks for the prompt response and change. Im sure this rabbit hole will get deeper before it all rolls back up. But might aswell get started.

**Comment by natebosch** [comment]
I likely won't be able to get this published until early next week. I noticed that we have some code changes here that haven't been synced to our SDK and internally, I'll need to get that done before publishing.

**Comment by are** [comment]
Hi, this is blocking the NNBD release in `cbor`, which is blocking the NNBD in my library. Will this be released any time soon?

**Comment by are** [comment]
Could we at least get a ballpark estimate how long is this going to take? I imagine this may be blocking for a lot of folks. I understand that the "work" is already done, so the community cannot do anything more to help with this?

**Comment by natebosch** [comment]
https://pub.dev/packages/web_socket_channel/versions/2.0.0
