### ISSUE TITLE
Working with self signed certs

### ISSUE THREAD

**Issue by MderM** [dart-lang/web_socket_channel#15]
Any chance that this package will work with self signed certificates? HttpClient has a configurable callback for this. Would help a lot in prototyping stage...

**Comment by nex3** [comment]
`web_socket_channel` just forwards to `dart:io`'s `WebSocket` implementation, so I'm going to move this to the SDK repo.

**Comment by nex3** [comment]
This issue was moved to dart-lang/sdk#32921
