### ISSUE TITLE
Does sink have listen() method?

### ISSUE THREAD

**Issue by kaeyonbaker** [dart-lang/web_socket_channel#17]
In README.md, IOWebSocketChannel part has following sample code:
```
channel.sink.add("connected!");
  channel.sink.listen((message) {
    // ...
  });
```
But it seems that only stream can be listened.
Besides,when I am using
```
widget.channel.stream.listen((message) {
      print(message);
 });
```
I got nothing fired... Any help is appreciated!

**Comment by loint** [comment]
Hi @nex3
I'm happy if you can help us and close this issue with PR.

Thank you very much.

**Comment by nex3** [comment]
Fixed by https://github.com/dart-lang/web_socket_channel/pull/18.
