### ISSUE TITLE
WebSocketChannelException: WebSocket connection failed

### ISSUE THREAD

**Issue by MoLuoPro** [dart-lang/web_socket_channel#181]
import 'package:web_socket_channel/html.dart';
var channel =
HtmlWebSocketChannel.connect(Uri.parse('ws://localhost:8864'));
void initWebSocket() async {
    channel.stream.listen((message) {
      _handleSubmitted(message);
    });
}
void sendMessage(String data) {
    channel.sink.add(data);
}

run it in flutter web, and I get an error :
Error: WebSocketChannelException: WebSocket connection failed.

It seems HtmlWebSocketChannel has a bug.

my python tornado server cmd tells me :
TypeError: check_origin() takes 1 positional argument but 2 were given
ERROR:tornado.access:500 GET /ws (::1) 0.00ms

IOWebSocketChannel is right
It's a mistake to replace  IOWebSocketChannel with HtmlWebSocketChannel from native to web.
I hope this problem can be solved as soon as possible . Thank you!

bty, the official example in readme is outdated.  hope it can be updated
such as : import 'package:web_socket_channel/web_socket_channel.dart';
in fact ,it's io.dart

**Comment by natebosch** [comment]
This looks like a server side issue. The HtmlWebSocketChannel works in our tests.

If you can find a more specific behavior difference that you believe is a bug we can investigate.

**Comment by Snowcrash5** [comment]
This happened to me when the uri did not end with a forward slash. When I added it, it worked.
In this case, it would be `ws://localhost:8864/`

Happened only in flutter web.

**Comment by ahmeedev** [comment]
I'm also facing this same issue

![image](https://github.com/dart-lang/web_socket_channel/assets/75003816/b1f1ed5a-bfdd-4d52-8a81-79ca5ff53ad0)

**Comment by natebosch** [comment]
This issue is inactionable. If anyone has a complete minimal reproduction case to share (probably by filing a new issue) we can take take a closer look.
