### ISSUE TITLE
How can I catch "WebSocketException: Connection to '***#' was not upgraded to websocket" exception

### ISSUE THREAD

**Issue by duhanbalci** [dart-lang/web_socket_channel#182]
I am using the following code to connect the WebSocket server. When the connection is gone, the client trying to reconnect using the same code. But when i restart WebSocket server, i am getting " WebSocketChannelException: WebSocketChannelException: WebSocketException: Connection to 'https://example.com/ws#' was not upgraded to websocket" error. I want to catch that and try again. How can I catch that exception?

```dart
try {
  _ws = WebSocketChannel.connect(_url);
  _ws!.stream.listen((e) => _handleMessage(e), cancelOnError: true, onDone: onDone);
  print("ws: connected");
} catch (e) {
  print("ws error: $e");
}
```

**Comment by blablabla123-cell** [comment]
Can you provide a more detail response on that? Caus I face the same issue. I implemented a JWT websocket authorization where I check if the token is provided or valid and if not, I don't upgrade the websocket connection and then recieve this error. Can't handle the error on the flutter side

**Comment by Jineapple** [comment]
The connect method starts an asynchronous task, and the exception occurs later, that's why just a try-catch around the connect will not catch it. You can await the websocket .ready property to make sure that connection is either completed or failed, then a try-catch will work.

**Comment by tsirolnik** [comment]
If a try/catch around the WebSocketChannel.connect fails then wrap the .ready attribute

```dart
_channel = WebSocketChannel.connect(Uri.parse(_url));
try {
  await _channel?.ready;
} catch (e) {
  print('WebSocket connection failed: $e');
}
```

dart flutter async websocket exception handle

**Comment by aimer63** [comment]
> If a try/catch around the WebSocketChannel.connect fails then wrap the .ready attribute
> 
> ```dart
> _channel = WebSocketChannel.connect(Uri.parse(_url));
> try {
>   await _channel?.ready;
> } catch (e) {
>   print('WebSocket connection failed: $e');
> }
> ```
> 
> dart flutter async websocket exception handle

This will simply print something like 
```dart 
 WebSocketChannelException: Instance of 'WebSocketException'
```
I didn't find how to extract more information about the exception, someone knows?
Even doing this:
```dart
try {
  await _channel.ready;
} catch(e) {
      final we = e as WebSocketChannelException;
      final we1 = we.inner as WebSocketException;
     print('${we1.message}');
}
```
it spits :
```
Unhandled Exception: type 'WebSocketException' is not a subtype of type 'WebSocketException' in type cast where
  WebSocketException is from package:web_socket/src/web_socket.dart  
  WebSocketException is from dart:_http
```
What I'm missing?

**Comment by t-walker-wei** [comment]
Help need here, thanks for any reply. I also face the same issue. I cannot connect to wss websocket server, I want to debug what is the issue, but cannot extract more information about the WebSocketChannelException, only get .
`WebSocketChannelException: Instance of 'WebSocketException'`

**Comment by msuddaby** [comment]
> Help need here, thanks for any reply. I also face the same issue. I cannot connect to wss websocket server, I want to debug what is the issue, but cannot extract more information about the WebSocketChannelException, only get . `WebSocketChannelException: Instance of 'WebSocketException'`

This worked for me

```
if (error is WebSocketChannelException) {
          if (error.inner != null) {
            final err = error.inner as dynamic;
            print('Websocket inner error: ${err.message.toString()}');
          }
          print('Websocket error: ${error.message}');
}
```

**Comment by mahendra022** [comment]
> > Help need here, thanks for any reply. I also face the same issue. I cannot connect to wss websocket server, I want to debug what is the issue, but cannot extract more information about the WebSocketChannelException, only get . `WebSocketChannelException: Instance of 'WebSocketException'`
> 
> This worked for me
> 
> ```
> if (error is WebSocketChannelException) {
>           if (error.inner != null) {
>             final err = error.inner as dynamic;
>             print('Websocket inner error: ${err.message.toString()}');
>           }
>           print('Websocket error: ${error.message}');
> }
> ```

that's work
