### ISSUE TITLE
Listening for incomming messages lags on Android hardware.

### ISSUE THREAD

**Issue by robertpiosik** [dart-lang/web_socket_channel#190]
I have following problem with the library; App running on an android device stops receiving messages after about 1 minute, then after a few minutes they are all delivered in bulk, then app works as it should for some time and problem repeats.

Everything is working fine in the Android/iOS emulators or iOS hardware.

**Comment by RobotKSR** [comment]
Same problem here. I think we should try to use another websocket plugin.

**Comment by robertpiosik** [comment]
Hi, the problem stopped from occurring for unknown reason.

**Comment by RobotKSR** [comment]
> Hi, the problem stopped from occurring for unknown reason.

It seems for me this problem happens in debug mode, but in release mode everything is being received fine for now.
