### ISSUE TITLE
How to configure connection timeout?

### ISSUE THREAD

**Issue by nailgilaziev** [dart-lang/web_socket_channel#22]
On mobile connection quality can vary depending on the environment conditions. 
And if connection is bad sometimes connecting to websocket servers can't be established because of ConnectionTimeOut. 
`WebSocketChannelException: WebSocketChannelException: SocketException: OS Error: Connection timed out, errno = 110, address = 192.168.2.2, port = 56472`

Currently is around a 2min. 
This is too long for creating a realtime applications, and sometimes we need to fail faster. 
How this timeout can be configured?

This behaviour is annoying because of https://github.com/dart-lang/web_socket_channel/issues/21

**Comment by nex3** [comment]
I don't believe either `dart:io` or `dart:html`'s `WebSocket` implementations, which this wraps, expose any way of configuring the timeout. Unless they both do, this package can't either.

**Comment by nailgilaziev** [comment]
in examples there are  this code: 
```
var client = new HttpClient();
      var request = await client.openUrl(
          "GET", Uri.parse("http://localhost:${server.port}"));
      request.headers
        ..set("Connection", "Upgrade")
        ..set("Upgrade", "websocket")
        ..set("Sec-WebSocket-Key", "x3JJHMbDL1EzLkh9GBhXDw==")
        ..set("Sec-WebSocket-Version", "13");

      var response = await request.close();
      var socket = await response.detachSocket();
      var innerChannel = new StreamChannel<List<int>>(socket, socket);
      var webSocket = new WebSocketChannel(innerChannel, serverSide: false);
```

May be it possible to configure in that maner?

**Comment by kavinda1995** [comment]
I did this way

https://github.com/dart-lang/web_socket_channel/issues/61#issuecomment-585564273
