### ISSUE TITLE
Is there any support in socket.io ?

### ISSUE THREAD

**Issue by CircleCurve** [dart-lang/web_socket_channel#23]
I have searched the flutter packages. And try to use web socket to connect socket.io. Seems like there is no support for socket.io client ???

**Comment by nex3** [comment]
This supports the [WebSocket protocol](https://tools.ietf.org/html/rfc6455), and can connect to any server that supports that protocol as well.

**Comment by marianoarga** [comment]
@nex3 Do you know any websocket server technology currently working with web_socket_channel?
