### ISSUE TITLE
web_socket_channel 2.3.0 - IOWebSocketChannel.connect Doesn't Handle SocketException

### ISSUE THREAD

**Issue by knnkrt** [dart-lang/web_socket_channel#249]
When I close the internet connection to test what happens in onDone method,  

Trying to handle exception but it doesn't handle;

```
try {
  _channel = IOWebSocketChannel.connect(
   Uri.parse("wss://MY_URL.com/ws/"),
  );
} on SocketException {
  print("HANDLE");
}
```

This code works on web_socket_channel version 2.2.0 (even I don't need to use) but on version 2.3.0 I'm getting:

```
SocketException (SocketException: Failed host lookup: 'MY_URL.com' (OS Error: No address associated with hostname, errno = 7))
```

**Comment by michpolicht** [comment]
Same issue with `WebSocketChannel`

```
  try {
    WebSocketChannel.connect(Uri.parse("ws://dupa.com"));
  } catch (e) {
    debugPrint("exception $e");
  }
```
It's impossible to handle the exception

**Comment by nicoroy2561** [comment]
Having the same issue, to me being a Timeout whenever I hot restart.

**Comment by tmtong** [comment]
`Uri uri = Uri.parse('ws://$host:${port.toString()}');
    try {
      socket = WebSocketChannel.connect(uri);
    } catch (e) {
      retryReconnect();
      return;
    }
    socket.stream.listen((message) {
      handlePacket(message);
    }, onError: (error) async {
      // debugPrint("onerror $error.toString()");

      retryReconnect();
      return;
    }, onDone: () async {
      // debugPrint("ondone ");

      retryReconnect();
      return;
    });`

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = 127.0.0.1, port = 48482

**Comment by MousyBusiness** [comment]
I've just tested web_socket_channel 2.2.0 and 2.3.0 and both have the same issue. I believe why we're now seeing this bug is because of iOS16 (except maybe the linux guy), from what I can tell, it reclaims the port after ~1 minute in background (unless something has changed somewhere else in my setup which I've not accounted for).

### Work around 1 (create websocket directly)
```
    try {
      await WebSocket.connect(_buildWebsocketUri("/usr").toString()).then((ws) {
        final _channel = IOWebSocketChannel(ws);
      });
    } catch (e) {
      print(e);
      return;
    }
```

### Work around 2 (guarded zone)
```
    await runZonedGuarded<Future<void>>(() async {
      final _channel = WebSocketChannel.connect(
        _buildWebsocketUri("/usr"),
      );
    }, (err, stack) {
      print(err);
      print(stack);
    });
```

**Comment by tmtong** [comment]
Thanks @MousyBusiness 

This is what I end up using
```
  void retryReconnect() {
    if (reconnectTimer != null) {
      return;
    }
    reconnectTimer = Timer(const Duration(seconds: 1), () {
      reconnectTimer = null;
      connect();
    });
  }

  void connect() async {
    // Uri uri = Uri.parse('ws://' + host + ':' + port.toString());
    Uri uri = Uri.parse('ws://$host:${port.toString()}');

    await runZonedGuarded<Future<void>>(() async {
      socket = WebSocketChannel.connect(uri);
    }, (err, stack) {
      retryReconnect();
    });

    socket.stream.listen((message) {
      handlePacket(message);
    }, onError: (error) async {
      // debugPrint("onerror $error.toString()");

      retryReconnect();
      return;
    }, onDone: () async {
      // debugPrint("ondone ");

      retryReconnect();
      return;
    });
  }
```

**Comment by brianquinlan** [comment]
As of 2.3.0, the correct error handling formulation is:

```dart
final channel = WebSocketChannel.connect(Uri.parse('ws://example.com'));
try {
  await channel.ready;
} on SocketException catch (e) {
  // Handle the exception.
} on WebSocketChannelException catch (e) {
  // Handle the exception.
}
```

I have a PR out to clarify this: https://github.com/dart-lang/web_socket_channel/pull/272

And sorry for not managing this change better.
