### ISSUE TITLE
Add a WebSocketChannel.ready field

### ISSUE THREAD

**Issue by nex3** [dart-lang/web_socket_channel#25]
Because `IOWebSocketChannel.connect()` and `HtmlWebSocketChannel.connect()` are synchronous, there's no way for a caller to know when the connection has actually completed and the web sockets are ready to use. We should add a `Future ready` getter that completes when the connection is established, or throws an error if it fails. This error should *not* be top-leveled if it's uncaught, since it will also be sent through the stream itself and some callers may only listen on that.

See #21 and https://github.com/flutter/flutter/issues/18204.

**Comment by 1AlexFix1** [comment]
Maybe it will help today to know that the socket is connected and close
```connection() async {
    WebSocket ws = await WebSocket.connect('ws://echo.websocket.org');
    print('ws open');
    ws.listen(
      (data) {
        print(data);
      },
      onDone: () {
        ws.close();
        print('ws close onDone');
      },
      onError: (error) {
        ws.close();
        print('ws close error = $error');
      },
    );
    IOWebSocketChannel iows = IOWebSocketChannel(ws);
    iows.sink.add(('Hello, World!'));
  }
```

**Comment by nailgilaziev** [comment]
@nex3 hi!
please tell us, any updates on a this problem?

**Comment by nex3** [comment]
I'm no longer on the Dart team, so I'm not involved in the maintenance of this package anymore.

**Comment by nailgilaziev** [comment]
@nex3 Can you mention the person who is currently involved in maintenance of this package? Because issue (depending issues) is real and here for a long time. thanks!

**Comment by nex3** [comment]
I'm not sure who's maintaining it these days.

**Comment by artrmz** [comment]
@nex3 @nailgilaziev I have added such field and made a PR. Not sure if it's the cleanest solution (probably not since I am a newbie when it comes to Dart) but maybe someone wants to take a look and improve it there is anything to improve.

**Comment by wanjm** [comment]
hello , is there any one working on this ?

**Comment by NathanO14** [comment]
Any working solution on this? I can't detect the connection state from IOWebSocketChannel object.

**Comment by jasonminsookim** [comment]
This would be a useful feature for users who are somewhat new to Websockets.

**Comment by abhinavsingh** [comment]
Looks like authors of this library never developed a real world application (it works on my system syndrome).  Seriously, I am amazed that this issue is now open since mid 2018 and being tossed around the park.  Currently upon first connect, there is simply no way to know if the connection is ready.  How do you even build a real world app with this?

**Comment by guid-empty** [comment]
If you work with IO my workaround of this issue is to listen to inner websocket state, but it's ugly method and I will rewrite this appoach lated:


```
    _quoteSocketChannel = IOWebSocketChannel.connect(
      Uri.parse(SubscriptionEndpoint(token: jwt).path),
    );
    _quoteSocketChannel.stream.listen(logger.i);


    Timer.periodic(Duration(milliseconds: 200), (timer) {
      if (_quoteSocketChannel.innerWebSocket?.readyState == WebSocket.open) {
        timer.cancel();

        _quoteSocketChannel.stream.listen((message) {
          print(message);
        });

```

**Comment by vogtb** [comment]
I'm encountering this issue as well. Not a lot of good options to get around this.

**Comment by dadagov125** [comment]
Is it really that hard to add a connection state stream?

**Comment by AlexV525** [comment]
cc @kevmoo Kevin can you help us to triage this?

**Comment by kevmoo** [comment]
@brianquinlan @devoncarew – thoughts?

**Comment by tmtong** [comment]
Yo guys
I have a retrytTimer in onError and onDone, otherwise it is set to null
You just need to check if the retryTimer is null. That's all

**Comment by brianquinlan** [comment]
I plan on reviewing https://github.com/dart-lang/web_socket_channel/pull/240

Could anyone who has an opinion about this feature please take a look?

**Comment by Bungeefan** [comment]
**For others who have subscribed to this issue:**
It seems like this was "silently" implemented by https://github.com/dart-lang/web_socket_channel/pull/240.
