### ISSUE TITLE
WebSocketException: Connection to 'http://xxx.com:9999/chat#' was not upgraded to websocket

### ISSUE THREAD

**Issue by 6ag** [dart-lang/web_socket_channel#277]
The following code will report an error `WebSocketException: Connection to 'http://xxx.com:9999/chat#' was not upgraded to websocket` in `macOS`. But everything works fine when running on `Android` and `iOS`.

```dart
import 'package:web_socket_channel/io.dart';
import 'dart:io';

IOWebSocketChannel? _channel;

void connectSocket() async {
  try {
    HttpClient httpClient = HttpClient();
    httpClient.connectionTimeout = Duration(seconds: _connectionTimeout);
    WebSocket webSocket = await WebSocket.connect('ws://xxx.com:9999/chat', customClient: httpClient);
    _channel = IOWebSocketChannel(webSocket);
    _channel?.stream.listen(_onData, onError: _onError, onDone: _onDone, cancelOnError: true);
  } catch (e) {
    LogUtil.d("Error:${e.toString()}");
  }
}
```

Please help me to see how I should solve this problem, thanks.

**Comment by 6ag** [comment]
I have tried to use the sample code to establish a connection, but the same error will be reported, and I think the reason is not here.

```dart
import 'package:web_socket_channel/web_socket_channel.dart';
import 'package:web_socket_channel/status.dart' as status;

main() async {
  final wsUrl = Uri.parse('ws://localhost:1234')
  var channel = WebSocketChannel.connect(wsUrl);

  channel.stream.listen((message) {
    channel.sink.add('received!');
    channel.sink.close(status.goingAway);
  });
}
```

**Comment by 6ag** [comment]
There is a new discovery about this problem. I use `flutter build macos` to package and the connection is normal! Errors are reported only in `debug` mode.

**Comment by fooevr** [comment]
Same issue.

**Comment by 6ag** [comment]
It is caused by proxy software, I have solved it. Clear the proxy configured in Terminal, close the proxy software and restart the computer to solve the problem.
