### ISSUE TITLE
API for adding Header to Websocket request

### ISSUE THREAD

**Issue by Coder246** [dart-lang/web_socket_channel#278]
In order to implement authorization to my websocket system on the backend. I want to add a header to the websocket request. Sadly I didn't find an API for that purpose.

**Comment by jinliyuelong** [comment]
how to set head

**Comment by quetool** [comment]
Did you managed to do it @coder246 ?

**Comment by beheobong** [comment]
Try this: https://stackoverflow.com/a/41521871 . It is ok

**Comment by timarnoldev** [comment]
> Did you managed to do it @coder246 ?

According to websocket specs custom headers are not mentioned and not implemented by the majority of browser engines. Thereby there shouldn't be used even if technically possible.
