### ISSUE TITLE
Some Exceptions cannot be Handled

### ISSUE THREAD

**Issue by Nabinda** [dart-lang/web_socket_channel#280]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Connection failed (OS Error: Network is unreachable, errno = 101)
 
 When the device is not connected on internet then this issues occurs which cannot be handled

**Comment by natebosch** [comment]
What have you tried to handle this exception? Do you have a reproduction you can share?

**Comment by Nabinda** [comment]
```
try {
      socket = IOWebSocketChannel.connect(SocketConfig.mainUrl);
      _messageController = StreamController<dynamic>.broadcast();
      socket.stream.listen(
        _onMessageReceived,
        onError: onError,
        onDone: onDone,
      );
    } catch (e) {
      onError(e);
    }
```
    
    
This is how I was trying to handle the issue however it was not working, this issue occurs when you try to connect the socket when device is not connected to internet

**Comment by brianquinlan** [comment]
@Nabinda could you try?
try {
  socket = IOWebSocketChannel.connect(SocketConfig.mainUrl);
  await socket.ready;  // Show throw if the connection cannot be established.
} catch (e) {
  onError(e);
}
```

**Comment by NaveenNirban** [comment]
> @Nabinda could you try?
> 
> ```dart
> try {
>   socket = IOWebSocketChannel.connect(SocketConfig.mainUrl);
>   await socket.ready;  // Show throw if the connection cannot be established.
> } catch (e) {
>   onError(e);
> }
> ```

Thanks buddy, it worked for me in case of **Server not available**. I was intentionally trying catch this exception but was not finding any ways to do it. It would be great any explanation is there regarding `await socket.ready;` and why traditional catch is not able to handle this.
