### ISSUE TITLE
Unable to add dependency 2.4.1

### ISSUE THREAD

**Issue by cjcj125125** [dart-lang/web_socket_channel#305]
Because every version of flutter_test from sdk depends on web 0.3.0 and web_socket_channel >=2.4.1 depends on web ^0.4.0, flutter_test from sdk is incompatible with web_socket_channel >=2.4.1.
So, because clean_mobile depends on both web_socket_channel ^2.4.1 and flutter_test from sdk, version solving failed.

How can I fix it？

**Comment by NotTsunami** [comment]
There's no fixes/feature included in 2.4.1, only some documentation/example improvements and a move to `package:web` to support WebAssembly compilation, so you're not missing any mission critical changes by any means.

The fix would be for this package to allow a wider range of version for `package:web` as mentioned in [this comment](https://github.com/dart-lang/web_socket_channel/pull/294#discussion_r1408422891).
