### ISSUE TITLE
2.4.1 seems to have introduced breaking changes

### ISSUE THREAD

**Issue by KammererTob** [dart-lang/web_socket_channel#307]
I've noticed that my package which depends on `web_socket_channel` suddenly has a "Analysis Issue" in pub.dev (https://pub.dev/packages/stomp_dart_client/score). This seems to be because of a breaking change introduced in 2.4.1. The change in question seems to be a move to the `web` package for the HTML WebSocket implementation.
Here is part of my code which is breaking because of that:

```
  final completer = Completer<HtmlWebSocketChannel>();
  final webSocket = WebSocket(config.connectUrl)
    ..binaryType = BinaryType.list.value;
  webSocket.onOpen.first.then((value) {
    completer.complete(HtmlWebSocketChannel(webSocket));
  });
```

Previously `HtmlWebSocketChannel` was expecting a `WebSocket` from the `dart:html` library. After 2.4.1 it seems to be expecting it from the `package:web` package.

Was this intentional? I am a bit hesitant to also move my project to the `web` package since it currently is still flagged as "highly experimental"  (https://github.com/dart-lang/web)

Related closed issue in the pub.dev repo: https://github.com/dart-lang/pub-dev/issues/7327

**Comment by devoncarew** [comment]
Do you mind posting the analysis issue you see?

**Comment by KammererTob** [comment]
I have fixed the dependency in the current version, so the analysis issue is no longer visible on the page. But here is a screenshot:
![image](https://github.com/dart-lang/web_socket_channel/assets/1510949/b6752b13-5433-4855-8eb2-e337e6b67458)

**Comment by devoncarew** [comment]
Thanks for the report! It looks like the port to package:web was unintentionally a breaking API change. This should have been done in a new major version of this package (`3.0.0`). We'll need to do some cleanup here, which may involve reverting the 2.x version of this package to continue to use dart:html, and re-publishing the package:web based version as 3.0.0.

**Comment by devoncarew** [comment]
I'm going to close this as the issue has mostly been addressed. If people find new breaking changes please re-open or create a new issue.

**Comment by KammererTob** [comment]
Thanks for addressing this so quickly!
