### ISSUE TITLE
Error: The getter 'EventStreamProviders' isn't defined for the class 'WebSocket'.

### ISSUE THREAD

**Issue by betimer** [dart-lang/web_socket_channel#316]
Version: 2.4.2

If downgrade to version 2.4.0, it is working well.

```
The getter 'EventStreamProviders' isn't defined for the class 'WebSocket'.
 - 'WebSocket' is from 'package:web/src/dom/websockets.dart' ('/C:/Users/betim/AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/dom/websockets.dart').
 - ```

**Comment by paddymahadeva** [comment]
we are facing the same issue, but we are not using web_socket directly. So no option to even downgrade as well

`Error: The getter 'EventStreamProviders' isn't defined for the class 'WebSocket'.`

**Comment by mogol** [comment]
@paddymahadeva you can add this to your pubspec.yaml

```
dependency_overrides: 
  web_socket_channel: 2.4.0
```

**Comment by devoncarew** [comment]
Thanks for the report! De-duping this with https://github.com/dart-lang/web_socket_channel/issues/318.
