### ISSUE TITLE
Simplify the web_socket_channel implementation

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/web_socket_channel#340]
There are two components:
1. reimplement `web_socket_channel` in terms of `package:web_socket`
2. remove the [`WebSocketChannel` constructor](https://github.com/dart-lang/web_socket_channel/blob/ced3a37193f89d5ee95792f342eeb15d3d55d8c1/lib/src/channel.dart#L125C3-L125C19) (the only known usage is in [`package:shelf_web_socket`](https://github.com/dart-lang/shelf/blob/68cb8641c3181cc76006887a7e93b9d3a423f590/pkgs/shelf_web_socket/lib/src/web_socket_handler.dart#L83)).

Steps:
- [X] Update `package:shelf_web_socket` to not rely on the `WebSocketChannel` constructor [PR](https://github.com/dart-lang/shelf/pull/423)
- [x] Update `package:web_socket_channel`:
  - [x] implement functionality in terms of `package:web_socket` [PR](https://github.com/dart-lang/web_socket_channel/pull/339)
  - [x] Remove `WebSocketChannel` constructor and make that class an `interface`
- [x] Publish `package:web_socket_channel` 3.x (branch: v3_release) [PR](https://github.com/dart-lang/web_socket_channel/pull/347)
- [x] Update `package:shelf_web_socket` to accept `package:web_socket_channel` 3.x (branch: v2_release) [PR](https://github.com/dart-lang/shelf/pull/425)
- [x] Publish `package:shelf_web_socket` 2.x
- [x] Update `package:test` to accept `package:web_socket_channel` 3.x and `package:shelf_web_socket` 2.x (branch: web_socket_version_constraints) [PR](https://github.com/dart-lang/test/pull/2204)
- [x] Publish `package:test`

**Comment by NotTsunami** [comment]
This should actually fix the issue I outlined in https://github.com/dart-lang/web_socket_channel/issues/237#issuecomment-1971592315. Looking forward to seeing this land.

**Comment by NotTsunami** [comment]
Should there be a corresponding task for `build_runner` to get updated? It still [explicitly](https://github.com/dart-lang/build/blob/master/build_runner/pubspec.yaml#L47) relies on 2.x.

**Comment by brianquinlan** [comment]
@NotTsunami Is `build_runner` part of a dependency cycle with `web_socket_channel`? My intent was not to update every package that relies on `web_socket_channel`, just the ones that make `web_socket_channel` unusable without the update.

**Comment by bc-lee** [comment]
I think `build_runner` is a 1p package, as well as `web_socket_channel`, so it should be dealt with breaking changes in `web_socket_channel` by updating `build_runner` to use the new version of `web_socket_channel`.

It seems that `build_runner` and `build_daemon` use `web_socket_channel`, but they aren't affected by the breaking change in `web_socket_channel` 3.0.0 in the library code.

However, `build_runner`'s test code is affected by the breaking change of `web_socket_channel` 3.0.0. This [code](https://github.com/dart-lang/build/blob/5eb5d9bf419b43252c7f1a41d47f334ab675e654/build_runner/test/server/serve_handler_test.dart#L317) uses the removed constructor of WebSocketChannel in web_socket_channel 3.0.0.

Other than this, the following patch seems to be enough to fix the dependency issue in https://github.com/dart-lang/build.

```patch
--- a/build_daemon/pubspec.yaml
+++ b/build_daemon/pubspec.yaml
@@ -15,10 +15,10 @@ dependencies:
   path: ^1.8.0
   pool: ^1.5.0
   shelf: ^1.0.0
-  shelf_web_socket: ^1.0.0
+  shelf_web_socket: ">=1.0.0 <3.0.0"
   stream_transform: ^2.0.0
   watcher: ^1.0.0
-  web_socket_channel: ^2.0.0
+  web_socket_channel: ">=2.0.0 <4.0.0"

 dev_dependencies:
   analyzer: '>=3.4.0 <7.0.0'
--- a/build_runner/pubspec.yaml
+++ b/build_runner/pubspec.yaml
@@ -39,12 +39,12 @@ dependencies:
   pub_semver: ^2.0.0
   pubspec_parse: ^1.0.0
   shelf: ^1.0.0
-  shelf_web_socket: ^1.0.0
+  shelf_web_socket: ">=1.0.0 <3.0.0"
   stack_trace: ^1.10.0
   stream_transform: ^2.0.0
   timing: ^1.0.0
   watcher: ^1.0.0
-  web_socket_channel: ^2.0.0
+  web_socket_channel: ">=2.0.0 <4.0.0"
   yaml: ^3.0.0

 dev_dependencies:
```

**Comment by brianquinlan** [comment]
I'll try to land upstream patches.

**Comment by brianquinlan** [comment]
@bc-lee Is this block you somehow? Could you [file an issue with `package:builder`](https://github.com/dart-lang/build/issues) and CC me?
