### ISSUE TITLE
Does this support onOpen event?

### ISSUE THREAD

**Issue by jsu93** [dart-lang/web_socket_channel#70]
The original package `Websocket` support `onOpen` event, but I didn't see any documentation about this in this repo's doc.

**Comment by jsu93** [comment]
https://api.dartlang.org/stable/2.4.0/dart-html/WebSocket/onOpen.html

**Comment by natebosch** [comment]
You should be able to use the `onOpen` from the underlying `WebSocket` used to construct a `WebSocketChannel`...

More discussion in #69  - closing as a duplicate.
