### ISSUE TITLE
My websocket app work on debug mode but doesn't on release mode

### ISSUE THREAD

**Issue by hariangr** [dart-lang/web_socket_channel#76]
I use 
`IOWebSocketChannel channel = IOWebSocketChannel.connect(#Some local websocket ip);`

**Comment by natebosch** [comment]
Is this flutter? It likely has to do with your permissions or similar. We don't really have the expertise to help with that here, you'd get better help from the flutter team.

https://github.com/flutter/flutter/issues/29688

**Comment by hariangr** [comment]
IT DOES ACTUALLY FIXED IT!!!
Like how? internet permission is ON by default on debug mode or something?

But I think I don't need to have this permission just to access internet in the past? I don't get it

The important thing is, now it works

*Sorry for my late reply, got busy with college

**Comment by Asadbekinha** [comment]
Same error

**Comment by devb** [comment]
> IT DOES ACTUALLY FIXED IT!!! Like how? internet permission is ON by default on debug mode or something?
> 
> But I think I don't need to have this permission just to access internet in the past? I don't get it
> 
> The important thing is, now it works
> 
> *Sorry for my late reply, got busy with college

How did you solve it Hari?? Please suggest as I'm facing the same issue.. Socket as well as this Agora both are working fine in debug mode but not in release mode.
Thanks

**Comment by hariangr** [comment]
> > IT DOES ACTUALLY FIXED IT!!! Like how? internet permission is ON by default on debug mode or something?
> > But I think I don't need to have this permission just to access internet in the past? I don't get it
> > The important thing is, now it works
> > *Sorry for my late reply, got busy with college
> 
> How did you solve it Hari?? Please suggest as I'm facing the same issue.. Socket as well as this Agora both are working fine in debug mode but not in release mode. Thanks

Sorry I dont quite remember it since it has been awhile. But internet permission is in fact on by default in DEBUG mode while it is not in RELEASE.

I would suggest you to add internet permission to android manifest xml file in release folder of android. If that doesnt work make sure your websocket is behind HTTPS. (I believe Android block http by default now). I think theres clearText option somewhere to force allow http

**Comment by devb** [comment]
> > > IT DOES ACTUALLY FIXED IT!!! Like how? internet permission is ON by default on debug mode or something?
> > > But I think I don't need to have this permission just to access internet in the past? I don't get it
> > > The important thing is, now it works
> > > *Sorry for my late reply, got busy with college
> > 
> > 
> > How did you solve it Hari?? Please suggest as I'm facing the same issue.. Socket as well as this Agora both are working fine in debug mode but not in release mode. Thanks
> 
> Sorry I dont quite remember it since it has been awhile. But internet permission is in fact on by default in DEBUG mode while it is not in RELEASE.
> 
> I would suggest you to add internet permission to android manifest xml file in release folder of android. If that doesnt work make sure your websocket is behind HTTPS. (I believe Android block http by default now). I think theres clearText option somewhere to force allow http

But, the other data from APIs are coming properly.. only the socket is not working.. will that be INTERNET permission issue still?? what do you say?

**Comment by dewunmirokeeb** [comment]
@devb  were you able to resolve this issue, i am currently facing the same issue, i have already added permission to allow internet in android manifest

**Comment by geryruslandi** [comment]
https://docs.flutter.dev/data-and-backend/networking
for anyone that still facing the issue
