### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Invalid argument(s)

### ISSUE THREAD

**Issue by Claus1** [dart-lang/web_socket_channel#77]
When sending a string to the server using IOWebSocketChannel the sending is ok.
But when the argument is an array of strings, got the topic exception.

> serverChannel.sink.add(result);

**Comment by parthpitorda** [comment]
@Claus1 are you done with this?
i have same issue right now

**Comment by Claus1** [comment]
@parthpitorda  IOWebSocketChannel has a lot of errors in Websocket protocol.
 Any server with  checking of sending data reports about errors. Examples:
https://github.com/Kai-Bailey/WebSock/issues/6
https://github.com/Kai-Bailey/WebSock/issues/5
 Only I ve found that works with it - https://pypi.org/project/SimpleWebSocketServer/
The developers as I see dont case about it.

**Comment by natebosch** [comment]
Can you clarify what you believe the bug is? Do you have a minimal reproduction?

**Comment by Claus1** [comment]
@natebosch I can repeat the message from the registered issue:
`I do not use emulator, only Linux native flutter app. Initialization and sending first package server-to-client is ok. Sending client->server such json ['1','2','3', 3] causes 'Received Invalid Data Frame' and closing socket. Why and where is problem in Websock is not clear. I see only the message in console:
<socket.socket fd=24, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 1234), raddr=('127.0.0.1', 54486)> closed
and same ws.log about invalid frame.`

Any other websocket clients (I tried some emulated ones in Python) does not cause such problem. What it is and where I don't know. Net protocols are not my field(

**Comment by natebosch** [comment]
@ZichangG - is this something you may be able to investigate at all?
