### ISSUE TITLE
in WEB project throws exception: NoSuchMethodError: invalid member on null: 'openUrl'

### ISSUE THREAD

**Issue by tomnvc** [dart-lang/web_socket_channel#82]
IOWebSocketChannel not working in WEB project (Linux platform).

.connect(....) throws exception: NoSuchMethodError: invalid member on null: 'openUrl'

_channel = new IOWebSocketChannel.connect('wss://$_url/');

**Comment by tomnvc** [comment]
interesting fact.. upon very first call on .connect(.....) exception is this:
**Unsupported operation: Platform._version**
and then all of the following calls give:
**NoSuchMethodError: invalid member on null: 'openUrl'**

**Comment by natebosch** [comment]
We do not expect `IOWebSocketChannel` to work on the web. It's specifically for platforms that support `dart:io`.

**Comment by tomnvc** [comment]
yeah... i figured that out :) but thank you!
how ever you should probably put up sample for that...
