### ISSUE TITLE
Error connection on android 

### ISSUE THREAD

**Issue by jfajardo** [dart-lang/web_socket_channel#88]
I have this error on Android device
`Caught error: WebSocketChannelException: WebSocketChannelException: WebSocketException: 
  Connection to 'https://localhost:0/ws' .....  was not upgraded to websocket`

Why change the ws url if it is ws://localhost/ws/ ?

**Comment by cs118651** [comment]
+1

**Comment by biij5698** [comment]
+1

**Comment by petekblaz** [comment]
+1
