### ISSUE TITLE
Error: Not found: 'dart:html'

### ISSUE THREAD

**Issue by PembaTamang** [dart-lang/web_socket_channel#95]
I am stuck with the following error in flutter after upgrading I am on the stable channel with the latest build

Compiler message:

```
lib/views/note_detail.dart:1:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
/F:/Flutter/flutter/packages/flutter/lib/src/painting/_network_image_web.dart:64:12: Error: Method not found: 'webOnlyInstantiateImageCodecFromUrl'.
    return ui.webOnlyInstantiateImageCodecFromUrl(resolved); // ignore: undefined_function
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
U
nhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ahtml; message=Standard
FileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      asFileUri (package:vm/kernel_front_end.dart:604:37)
#2
      writeDepfile (package:vm/kernel_front_end.dart:799:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:472:15)
<asynchronous suspension>
#4     
 _FlutterFrontendCompiler.compile (package:flutter_frontend_server/server.dart:38:22)
#5      starter (package:flutter_frontend_server/server.dart:
149:27)
#6      main (file:///C:/b/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:8:30)
#7      _startIsolate.<anonymous closure> (dart:isolat
e-patch/isolate_patch.dart:305:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.
```

* Where:
Script 'F:\Flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'F:\Flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

**Comment by natebosch** [comment]
When pasting output or code please remember to use [code fence](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks)

It looks like you are trying to import a web specific library from an app compiled for mobile. That is not possible. If it is specifically coming from this package you can import `package:web_socket_channel/web_socket_channel.dart` or `package:web_socket_channel/io.dart` on mobile.

You can import `package:web_socket_channel/web_socket_channel.dart` or `package:web_socket_channel/html.dart` on web.

For cross platform apps you can either restrict it to `package_web_socket_channel/web_socket_channel` or use [conditional imports](https://dart.dev/guides/libraries/create-library-packages#conditionally-importing-and-exporting-library-files) to pick different imports based on the available platform libraries.

**Comment by Artem738** [comment]
Perhaps universal_html will help you solve this problem. 

    import 'package:universal_html/html.dart' as html;

**Comment by natebosch** [comment]
We won't be using `universal_html` from this package - we don't expect anyone outside of web apps to import the web specific libraries.

**Comment by mrdc** [comment]
> For cross platform apps you can either restrict it to `package_web_socket_channel/web_socket_channel`

Will you be so kind to provide more details? Do you mean `import 'package:web_socket_channel/web_socket_channel.dart';`?
It doesn't fixes the issue.

**Comment by natebosch** [comment]
> Do you mean `import 'package:web_socket_channel/web_socket_channel.dart';`?
> It doesn't fixes the issue.

Yes. That is what I mean. That must be the only import into this package.

**Comment by mrdc** [comment]
> Yes. That is what I mean. That must be the only import into this package.

Unfortunately, it doesn't work for me:

`Undefined name 'HtmlWebSocketChannel'.`
`Undefined name 'IOWebSocketChannel'.`
`Unused import: 'package:web_socket_channel/web_socket_channel.dart'.`
