### ISSUE TITLE
can I use web_socket_channel in server side?

### ISSUE THREAD

**Issue by note8g2018** [dart-lang/web_socket_channel#99]
can I use web_socket_channel in server side? if it yes, then How? is there a good tutorial?
how about use it with Aqueduct Framework?

**Comment by natebosch** [comment]
Yes, you can create an `IOWebSocketChannel` wrapping a `WebSocket`

I don't know about aqueduct specifically, you might want to reach out to the author or on stack overlow.

The docs are at https://pub.dev/documentation/web_socket_channel/latest/web_socket_channel.io/IOWebSocketChannel/IOWebSocketChannel.html
https://api.dart.dev/stable/2.7.1/dart-io/WebSocket-class.html
